

[http]
  [http.routers]
    [http.routers.%%PROJECT_NAME%%_production_app]
      entryPoints = ["web"]
      rule = "Host(`%%PRODUCTION_URL_APP%%`)"
      service = "%%PROJECT_NAME%%_production_app"
      middlewares = ["httpsredirect"]

    [http.routers.%%PROJECT_NAME%%_production_app-secure]
      entryPoints = ["websecure"]
      rule = "Host(`%%PRODUCTION_URL_APP%%`)"
      service = "%%PROJECT_NAME%%_production_app"
      [http.routers.%%PROJECT_NAME%%_production_app-secure.tls]
        certResolver = "mytlschallenge"

    [http.routers.%%PROJECT_NAME%%_production_admin]
      entryPoints = ["web"]
      rule = "Host(`%%PRODUCTION_URL_ADMIN%%`)"
      service = "%%PROJECT_NAME%%_production_admin"
      middlewares = ["httpsredirect"]

    [http.routers.%%PROJECT_NAME%%_production_admin-secure]
      entryPoints = ["websecure"]
      rule = "Host(`%%PRODUCTION_URL_ADMIN%%`)"
      service = "%%PROJECT_NAME%%_production_admin"
      [http.routers.%%PROJECT_NAME%%_production_admin-secure.tls]
        certResolver = "mytlschallenge"

  [http.services]
    [http.services.%%PROJECT_NAME%%_production_app]
      [http.services.%%PROJECT_NAME%%_production_app.loadBalancer]
        [[http.services.%%PROJECT_NAME%%_production_app.loadBalancer.servers]]
          port = "3000"
          url = "http://%%PROJECT_NAME%%_production_app:3000"

    [http.services.%%PROJECT_NAME%%_production_mariadb]
      [http.services.%%PROJECT_NAME%%_production_mariadb.loadBalancer]
        [[http.services.%%PROJECT_NAME%%_production_mariadb.loadBalancer.servers]]
          port = "3306"
          url = "http://%%PROJECT_NAME%%_production_mariadb:3306"

    [http.services.%%PROJECT_NAME%%_production_admin]
      [http.services.%%PROJECT_NAME%%_production_admin.loadBalancer]
        [[http.services.%%PROJECT_NAME%%_production_admin.loadBalancer.servers]]
          port = "80"
          url = "http://%%PROJECT_NAME%%_production_admin:80"

    [http.services.%%PROJECT_NAME%%_production_adminer]
      [http.services.%%PROJECT_NAME%%_production_adminer.loadBalancer]
        [[http.services.%%PROJECT_NAME%%_production_adminer.loadBalancer.servers]]
          port = "8080"
          url = "http://%%PROJECT_NAME%%_production_adminer:8080"

  [http.middlewares]
    [http.middlewares.httpsredirect.redirectScheme]
      scheme = "https"

    [http.middlewares.basicauth.basicAuth]
      users = [
        "testuser:$apr1$7i5qo5wa$NBbY9salk11T3chQ4aeZD.",
      ]