[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.%%PROJECT_NAME%%_production_web]
    address = ":80"
  [entryPoints.%%PROJECT_NAME%%_production_websecure]
    address = ":443"
  [entryPoints.%%PROJECT_NAME%%_production_app]
    address = ":3000"
  [entryPoints.%%PROJECT_NAME%%_production_mariadb]
    address = ":3306"
  [entryPoints.%%PROJECT_NAME%%_production_admin]
    address = ":8081"
  [entryPoints.%%PROJECT_NAME%%_production_adminer]
    address = ":8080"

  [entryPoints.%%PROJECT_NAME%%_staging_web]
    address = ":80"
  [entryPoints.%%PROJECT_NAME%%_staging_websecure]
    address = ":443"
  [entryPoints.%%PROJECT_NAME%%_staging_app]
    address = ":3000"
  [entryPoints.%%PROJECT_NAME%%_staging_mariadb]
    address = ":3306"
  [entryPoints.%%PROJECT_NAME%%_staging_admin]
    address = ":8081"
  [entryPoints.%%PROJECT_NAME%%_staging_adminer]
    address = ":8080"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    network = "overlord_proxy"
    swarmMode = true
    exposedByDefault = true
  # Enable the file provider to define routers / middlewares / services in a file
  [providers.file]
    debugLogGeneratedTemplate = true
    directory = "/etc/traefik/dynamic"
    watch = true

[certificatesResolvers]
  [certificatesResolvers.mytlschallenge]
    [certificatesResolvers.mytlschallenge.acme]
      email = "mail@lacolonia.studio"
      storage = "/letsencrypt/acme.json"
      tlschallenge = true
